package com.neuedu.dao;

import com.neuedu.entity.Order;
import com.neuedu.entity.OrderItem;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);

    Order selectByuserIdAndOrderNo(@Param("userId") Integer userId,
                                   @Param("orderNo") long orderNo);

    List<Order> selectOrderByUserId(@Param("userId") Integer userId);

    Order selectByOrderNo(@Param("orderNo") Long orderNo);

    List<Order> selectBycreateTime(@Param("orderStatus") Integer orderStatus,@Param("time") String time);
}